# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pp_info.proto\"\xb4\x02\n\x07\x41ppInfo\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x16\n\x0e\x64ownload_count\x18\x02 \x01(\t\x12\x17\n\x0f\x61pp_description\x18\x03 \x01(\t\x12\x14\n\x0crating_score\x18\x04 \x01(\x02\x12/\n\x0csimilar_apps\x18\x05 \x03(\x0b\x32\x19.AppInfo.SimilarAppsEntry\x12\x16\n\x0e\x61pp_categories\x18\x06 \x03(\t\x12\x16\n\x0e\x64\x65veloper_name\x18\x07 \x01(\t\x12\x14\n\x0creview_count\x18\x08 \x01(\t\x12%\n\rmore_app_data\x18\t \x01(\x0b\x32\x0e.ExtractedData\x1a\x32\n\x10SimilarAppsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xec\x01\n\rExtractedData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x17\n\x0foperatingSystem\x18\x04 \x01(\t\x12\x1b\n\x13\x61pplicationCategory\x18\x05 \x01(\t\x12\x15\n\rcontentRating\x18\x06 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x07 \x01(\t\x12\x13\n\x0bratingValue\x18\x08 \x01(\x02\x12\x13\n\x0bratingCount\x18\t \x01(\x03\x12\r\n\x05price\x18\n \x01(\x02\x12\x15\n\rpriceCurrency\x18\x0b \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPINFO_SIMILARAPPSENTRY._options = None
  _APPINFO_SIMILARAPPSENTRY._serialized_options = b'8\001'
  _globals['_APPINFO']._serialized_start=19
  _globals['_APPINFO']._serialized_end=327
  _globals['_APPINFO_SIMILARAPPSENTRY']._serialized_start=277
  _globals['_APPINFO_SIMILARAPPSENTRY']._serialized_end=327
  _globals['_EXTRACTEDDATA']._serialized_start=330
  _globals['_EXTRACTEDDATA']._serialized_end=566
# @@protoc_insertion_point(module_scope)
